# Generated by Django 5.0.2 on 2024-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_rename_usern_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'List of Users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
