# Generated by Django 5.0.2 on 2024-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_reserveuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReserveUser',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('B', 'BOOKED'), ('C', 'CANCELLED')], default='B', max_length=200),
        ),
    ]
